[theme]
primaryColor = "#1DB954"  # Green color used by Spotify
backgroundColor = "#000000"  # Black background color
secondaryBackgroundColor = "#282828"  # Dark gray secondary background color
textColor = "#FFFFFF"  # White text color
font = "sans serif"  # Specify the font you want to use